CREATE TABLE contactdetail (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  detail VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;