DROP TABLE cronjobaction;

CREATE TABLE key_value (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  k VARCHAR(255) NOT NULL,
  v VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

