#include("lib/prototype.js")
#include("lib/effects.js")
#include("lib/scrollwork.js")
#include("scripts/Base_prototype.js")
#include("lib/CalendarPopupCompact.js")
#include("lib/dragdrop.js")
#include("scripts/Base_Calendar_prototype.js")